#ifndef SOAKPLAYER_SOAKSTATAUS_H
#define SOAKPLAYER_SOAKSTATAUS_H

#endif //SOAKPLAYER_SOAKSTATAUS_H

#define SOAK_THREAD_MAIN 1
#define SOAK_THREAD_CHILD 2

#define SOAK_FFMPEG_CAN_NOT_OPEN_URL 3
#define SOAK_FFMPEG_CAN_NOT_FIND_STREAMS 4
#define SOAK_FFMPEG_CAN_NOT_OPEN_URL 5
